### ISSUE TITLE
do not recreate file, just overwrite

### ISSUE THREAD

**Issue by runcom** [shishir-a412ed/docker-lvm-driver#19] opened 2016-03-02 15:32 UTC
https://github.com/shishir-a412ed/docker-lvm-plugin/blob/master/src/driver.go#L234

could you just use ioutil.WriteFile to always write it? no need to stat,remove,create I guess

**Comment by rhatdan** [comment] 2016-03-02 15:43
I agree.

**Comment by runcom** [comment] 2016-03-02 15:45
you can buffer the csv and then write to the file directly (but I hope to get rid of csv, and do the same with json)

**Comment by shishir-a412ed** [comment] 2016-03-03 00:52
@rhatdan @runcom
Both `ioutil.WriteFile` and `os.Create` truncates the file if it already exists.
IIRC I was doing a `os.Stat` and removing the existing file, because somehow earlier it was not truncating the file properly, and appending (messing) up the content.
So as a safety net I removed the original file and created a new one. I am not able to reproduce that error anymore. So I have remove that piece of code.

Just, `os.Create` should do the job now.

**Comment by rhatdan** [comment] 2016-03-03 14:22
@shishir-a412ed Close issue once you have pushed a fix into git.

**Comment by shishir-a412ed** [comment] 2016-03-03 16:24
Fixed in Master.

**Closed as completed by shishir-a412ed** 2016-03-03 16:24 UTC
Labels: bug
